<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>14.0</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Blazicons.Bootstrap" />
		<PackageReference Include="PodNet.Blazor.TypedRoutes" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ReactiveSamples.Common\ReactiveSamples.Common.csproj" />
		<ProjectReference Include="..\ReactiveValues.Blazor\ReactiveValues.Blazor.csproj" />
		<ProjectReference Include="..\ReactiveValues.DataTypes\ReactiveValues.DataTypes.csproj" />
	</ItemGroup>

</Project>
