<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net462;netstandard2.0;net10.0</TargetFrameworks>
		<LangVersion>14.0</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<Version>1.0.0-beta.2</Version>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/R2D221/ReactiveValues</PackageProjectUrl>
		<Description>C# reactive values inspired by JS signals. This package includes base classes to build objects with automatic PropertyChanged events.</Description>

		<MeziantouPolyfill_IncludedPolyfills>
			|M:System.ArgumentNullException.ThrowIfNull(System.Object,System.String)
			|M:System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd``1(`0,System.Func{`0,``0,`1},``0)
			|M:System.Collections.Generic.Dictionary`2.Remove(`0,`1@)
			|T:System.Diagnostics.CodeAnalysis.AllowNullAttribute
			|T:System.Diagnostics.CodeAnalysis.DisallowNullAttribute
			|T:System.Diagnostics.CodeAnalysis.DoesNotReturnAttribute
			|T:System.Diagnostics.CodeAnalysis.DoesNotReturnIfAttribute
			|T:System.Diagnostics.CodeAnalysis.MaybeNullAttribute
			|T:System.Diagnostics.CodeAnalysis.MaybeNullWhenAttribute
			|T:System.Diagnostics.CodeAnalysis.MemberNotNullAttribute
			|T:System.Diagnostics.CodeAnalysis.MemberNotNullWhenAttribute
			|T:System.Diagnostics.CodeAnalysis.NotNullAttribute
			|T:System.Diagnostics.CodeAnalysis.NotNullIfNotNullAttribute
			|T:System.Diagnostics.CodeAnalysis.NotNullWhenAttribute
			|T:System.Runtime.CompilerServices.CallerArgumentExpressionAttribute
		</MeziantouPolyfill_IncludedPolyfills>
		<MeziantouPolyfill_GenerateDebugFile>true</MeziantouPolyfill_GenerateDebugFile>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="..\Compatibility\Compatibility\**\*.cs" LinkBase="Compatibility" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Meziantou.Polyfill">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="TypeNameFormatter.Sources">
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		  <PrivateAssets>all</PrivateAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ReactiveValues\ReactiveValues.csproj" />
	</ItemGroup>

</Project>
