<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net462;net10.0-windows</TargetFrameworks>
		<LangVersion>14.0</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\ReactiveValues.Markup\ReactiveValues.Markup.csproj" />
		<ProjectReference Include="..\ReactiveValues.WindowsForms\ReactiveValues.WindowsForms.csproj" />
	</ItemGroup>

</Project>
