<Project Sdk="Microsoft.Build.NoTargets/3.7.134">

	<PropertyGroup>
		<TargetFrameworks>net8.0</TargetFrameworks>
		<LangVersion>14.0</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="Compatibility\**\*.cs" />
	</ItemGroup>

</Project>
