<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net462;net8.0</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="..\Compatibility\Compatibility\**\*.cs" LinkBase="Compatibility" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MSTest" />
		<PackageReference Include="PolySharp">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net462'">
		<PackageReference Include="System.Threading.Channels" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ReactiveValues\ReactiveValues.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
	</ItemGroup>

</Project>
