<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<LangVersion>14.0</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<!--<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />-->
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ReactiveValues.DataTypes\ReactiveValues.DataTypes.csproj" />
		<ProjectReference Include="..\ReactiveValues.Wpf\ReactiveValues.Wpf.csproj" />
	</ItemGroup>

</Project>
